"""llm_briefing.py — LLM-powered morning briefing for the credit risk dashboard.

Public API
----------
generate_morning_briefing(df: pd.DataFrame) -> dict
    Accepts the full model output DataFrame (one row per date) and returns a
    plain-English morning briefing generated by Claude.

    Return schema::

        {
            "text":   str | None,   # the briefing prose
            "date":   str | None,   # YYYY-MM-DD of the latest row
            "cached": bool,         # True when result came from disk cache
            "error":  str | None,   # non-None when something went wrong
        }

    The function is safe to call even when the Anthropic API key is absent or
    the API is unreachable — errors are caught and surfaced in the "error" key
    rather than raised.

Cache
-----
Results are persisted to ``history/briefing_cache.json`` (relative to the
project root, i.e. one level above ``src/``).  The cache is a JSON object
keyed by date string (YYYY-MM-DD).  If a cached entry exists for today's date
it is returned immediately without calling the API.
"""

from __future__ import annotations

import json
import os
import pathlib
from datetime import datetime, timezone
from typing import Any

import pandas as pd

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MODEL = "claude-haiku-4-5-20251001"
MAX_TOKENS = 400

# Path helpers (src/ sits one level inside the project root)
_SRC_DIR = pathlib.Path(__file__).resolve().parent
_PROJECT_ROOT = _SRC_DIR.parent
_CACHE_PATH = _PROJECT_ROOT / "history" / "briefing_cache.json"

# Columns we extract from the DataFrame
_SIGNAL_COLS = [
    "composite_risk_score_smooth",
    "final_decision",
    "hy_spread",
    "vix",
    "treasury_stress_score_smooth",
    "credit_market_risk_score_smooth",
    "macro_risk_score_smooth",
    "complacency_score_smooth",
    "shock_flag",
]


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _load_cache() -> dict[str, Any]:
    """Return the on-disk cache dict, or an empty dict if it does not exist."""
    if _CACHE_PATH.exists():
        try:
            with _CACHE_PATH.open("r", encoding="utf-8") as fh:
                return json.load(fh)
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


def _save_cache(cache: dict[str, Any]) -> None:
    """Write *cache* to disk, creating parent directories as needed."""
    _CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    with _CACHE_PATH.open("w", encoding="utf-8") as fh:
        json.dump(cache, fh, indent=2, default=str)


def _extract_state(df: pd.DataFrame) -> tuple[dict[str, Any], float | None, str]:
    """Return (latest_state_dict, delta_composite, date_str).

    *delta_composite* is the day-over-day change in composite_risk_score_smooth
    (latest minus second-to-last), or None when fewer than two rows exist.
    """
    if df.empty:
        raise ValueError("DataFrame is empty — cannot extract model state.")

    last_row = df.iloc[-1]

    # Resolve the date from a 'date' column or the index
    if "date" in df.columns:
        raw_date = last_row["date"]
    else:
        raw_date = df.index[-1]

    if isinstance(raw_date, (datetime, pd.Timestamp)):
        date_str = pd.Timestamp(raw_date).strftime("%Y-%m-%d")
    else:
        date_str = str(raw_date)[:10]

    state: dict[str, Any] = {}
    for col in _SIGNAL_COLS:
        if col in df.columns:
            val = last_row[col]
            # Convert numpy/pandas scalars to plain Python types
            if hasattr(val, "item"):
                val = val.item()
            state[col] = val
        else:
            state[col] = None

    # Day-over-day delta
    delta: float | None = None
    score_col = "composite_risk_score_smooth"
    if score_col in df.columns and len(df) >= 2:
        prev_val = df.iloc[-2][score_col]
        curr_val = last_row[score_col]
        try:
            delta = float(curr_val) - float(prev_val)
        except (TypeError, ValueError):
            delta = None

    return state, delta, date_str


def _build_prompt(state: dict[str, Any], delta: float | None, date_str: str) -> str:
    """Compose the user-turn prompt sent to Claude (kept under ~600 tokens)."""

    def fmt(val: Any, decimals: int = 2) -> str:
        if val is None:
            return "N/A"
        try:
            return f"{float(val):.{decimals}f}"
        except (TypeError, ValueError):
            return str(val)

    delta_str = (
        f"{delta:+.2f}" if delta is not None else "N/A"
    )

    shock = state.get("shock_flag")
    shock_str = "YES" if shock else "No"

    prompt = (
        f"Date: {date_str}\n\n"
        "Current credit risk model readings:\n"
        f"  Composite risk score (smoothed): {fmt(state.get('composite_risk_score_smooth'))}\n"
        f"  Day-over-day change in composite score: {delta_str}\n"
        f"  Final regime decision: {state.get('final_decision', 'N/A')}\n"
        f"  HY spread (bps): {fmt(state.get('hy_spread'), 0)}\n"
        f"  VIX: {fmt(state.get('vix'))}\n"
        f"  Treasury stress score (smoothed): {fmt(state.get('treasury_stress_score_smooth'))}\n"
        f"  Credit market risk score (smoothed): {fmt(state.get('credit_market_risk_score_smooth'))}\n"
        f"  Macro risk score (smoothed): {fmt(state.get('macro_risk_score_smooth'))}\n"
        f"  Complacency score (smoothed): {fmt(state.get('complacency_score_smooth'))}\n"
        f"  Shock flag triggered: {shock_str}\n\n"
        "Write exactly 3 short paragraphs (no headers, no bullet points, no markdown):\n"
        "1. Describe the current credit risk regime and what the key signals are saying.\n"
        "2. Explain what changed since yesterday based on the day-over-day composite score delta and any shock flag.\n"
        "3. State the practical implication for credit portfolio positioning today.\n\n"
        "Tone: professional, concise, suitable for a morning briefing to a credit portfolio manager. "
        "Each paragraph should be 2–3 sentences. Do not start paragraphs with 'Paragraph'."
    )
    return prompt


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_morning_briefing(df: pd.DataFrame) -> dict[str, Any]:
    """Generate a plain-English morning briefing from the current model state.

    Parameters
    ----------
    df:
        Full model output DataFrame with at least the columns listed in
        ``_SIGNAL_COLS`` and a ``date`` column (or DatetimeIndex).

    Returns
    -------
    dict with keys:
        * ``text``   — briefing prose (str) or None on error
        * ``date``   — YYYY-MM-DD of the latest row, or None on error
        * ``cached`` — True when the result was read from disk cache
        * ``error``  — error message string, or None on success
    """
    # ---- 1. Check for API key ------------------------------------------------
    api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if not api_key:
        return {
            "text": None,
            "date": None,
            "cached": False,
            "error": "ANTHROPIC_API_KEY not set",
        }

    try:
        # ---- 2. Extract model state ------------------------------------------
        state, delta, date_str = _extract_state(df)

        # ---- 3. Check cache --------------------------------------------------
        cache = _load_cache()
        if date_str in cache:
            entry = cache[date_str]
            return {
                "text": entry.get("text"),
                "date": date_str,
                "cached": True,
                "error": None,
            }

        # ---- 4. Build prompt and call the API --------------------------------
        import anthropic  # imported here so missing SDK doesn't break imports

        client = anthropic.Anthropic(api_key=api_key)

        user_prompt = _build_prompt(state, delta, date_str)

        message = client.messages.create(
            model=MODEL,
            max_tokens=MAX_TOKENS,
            system=(
                "You are a concise credit market analyst writing a morning briefing. "
                "Follow the user's paragraph instructions exactly."
            ),
            messages=[
                {"role": "user", "content": user_prompt},
            ],
        )

        # Extract text from the response
        briefing_text: str = ""
        for block in message.content:
            if hasattr(block, "text"):
                briefing_text += block.text

        briefing_text = briefing_text.strip()

        # ---- 5. Persist to cache ---------------------------------------------
        cache[date_str] = {
            "text": briefing_text,
            "generated_at": datetime.now(tz=timezone.utc).isoformat(),
        }
        _save_cache(cache)

        return {
            "text": briefing_text,
            "date": date_str,
            "cached": False,
            "error": None,
        }

    except Exception as exc:  # noqa: BLE001
        return {
            "text": None,
            "date": None,
            "cached": False,
            "error": str(exc),
        }
